# Generated by Django 5.1.3 on 2024-12-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
