# Generated by Django 5.1.3 on 2024-12-02 06:59

import utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_users_is_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=utils.id_generator.generate_unique_id, max_length=12, unique=True),
        ),
    ]
