# Generated by Django 5.1.3 on 2024-12-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_returnrequest_orderitem_alter_returnrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_until',
        ),
    ]
