# Generated by Django 5.1.3 on 2024-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productimage_is_delete_productvariant_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
