# Generated by Django 5.1.3 on 2024-11-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productimage_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_no',
        ),
    ]
