# Generated by Django 5.1.3 on 2024-11-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_users_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
