# Generated by Django 5.1.3 on 2024-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_users_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
