# Generated by Django 5.1.3 on 2024-11-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='disscount_type',
            new_name='discount_type',
        ),
    ]
