# Generated by Django 5.1.3 on 2024-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_disscount_type_offer_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='offer_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
