# Generated by Django 5.1.3 on 2024-11-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
